# secondary
heat_template_version: 2016-10-14

description: |
  #### CentOSv7 Secondary
  This is a nested stack that defines a single application minion,
  based on a vanilla CentOSv7 image.  This stack is included by
  a ResourceGroup resource in the parent template (primary.yaml).

parameter_groups:

parameters:

  name_map:
    type: json

  index:
    type: string

  server_name:
    hidden: true
    label: Server name (Do not change)
    type: string
    default: example-0

  server_flavor:
    label: Server Size
    description: |
      Use larger RAM sizes for production instances and 1GB for most dev and QA instances.
    type: string
    default: 1 GB General Purpose v1
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1

  server_image:
    hidden: true
    label: Operating System
    description: |
      CentOS v7 is the default OS that DMS supports for new systems.
    type: string
    default: CentOS 7 (PVHVM) (Orchestration)
    immutable: true

  ssh_key:
    hidden: true
    label: SSH key pair
    description: Name of SSH key pair to be used for compute instance
    type: string
    default: shared_initial_build_key
    constraints:
      - custom_constraint: nova.keypair

  parent_stack_id:
    hidden: true
    label: Parent Stack (Do not change)
    type: string
    default: None

resources:

  server:
    type: OS::Nova::Server
    properties:
      name: { get_param: [ name_map, { get_param: index } ] }
      key_name: { get_param: "ssh_key" }
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      metadata:
        rax-heat: { get_param: "parent_stack_id" }
        build_config: "monitoring_defaults"
      user_data_format: RAW
      config_drive: true
      user_data:
        str_replace:
          template: |
            #cloud-config
            package_upgrade: false
            runcmd:
              - git clone --depth=1 --branch=master http://10.223.80.79:3000/dms/server-setup.git /root/server-setup
              - /root/server-setup/initial_install.sh
              - /root/server-setup/hapee_install.sh
              - /root/server-setup/conformity_monkey.sh brandcloud-hapee-tests
              # Reboot upon successful deployment
              - systemctl reboot
          params:

outputs:
