# server.yaml
# Patrick M. Slattery - June 14th 2016

heat_template_version: 2016-04-08

parameters:

  image:
    label: Operating System
    type: string
    default: CentOS 7 (PVHVM)
    default: CentOS 7 (PVHVM)
    constraints:
    - allowed_values:
      - CentOS 7 (PVHVM)

  flavor:
    label: Server Size
    type: string
    default: 1 GB General Purpose v1
    default: 1 GB General Purpose v1
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1

  key_name:
    label: SSH key pair
    type: string
    default: shared_initial_build_key
    constraints:
      - custom_constraint: nova.keypair
      - allowed_values:
        - shared_initial_build_key
resources:

  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
      user_data_format: RAW
      config_drive: true
      user_data:
        str_replace:
          template: |
            #cloud-config
            package_upgrade: true
            write_files:
            - content: |
                [WANdisco-Git]
                name=WANdisco Git - CentOS 7
                baseurl=http://opensource.wandisco.com/centos/7/git/$basearch/
                enabled=1
                gpgcheck=1
                gpgkey=http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco
              owner: root:root
              path: /etc/yum.repos.d/wandisco-git.repo
              permissions: '0644'
            packages:
              - git

  entity:
    type: Rackspace::CloudMonitoring::Entity
    properties:
      label: { get_param: "OS::stack_name" }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }

  agent_token:
    type: Rackspace::CloudMonitoring::AgentToken
    properties:
      label: { get_param: "OS::stack_name" }

  cpu_check:
    type: Rackspace::CloudMonitoring::Check
    properties:
      entity: { get_resource: server }
      type: agent.cpu
      label: CPU check
      details: {}
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
      period: 30
      timeout: 10

outputs:
